version: '3.8'

x-postgres-env: &postgres-env
  POSTGRES_USER: candidate
  POSTGRES_PASSWORD: screencloudpwd
  POSTGRES_DB: screencloud-combined-db

x-postgres-volumes: &postgres-volumes
  - postgres_data:/var/lib/postgresql/data

x-order-service-port: &device-service-port
  - "3000:3000"

services:
  device-service:
    image: device-management-service
    container_name: device-management-service
    build:
      context: ./DeviceService
      dockerfile: ./Dockerfile
    ports: *device-service-port
    depends_on:
      - postgres
  postgres:
    image: postgres:15
    container_name: local-postgres
    environment: *postgres-env
    volumes: *postgres-volumes
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
